# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ master ]
#  release:
#    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
#        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
#        settings-path: ${{ github.workspace }} # location for the settings.xml file
        cache: maven
        server-id: chovy-rush-snapshot
        server-username: MAVEN_REPO_USERNAME
        server-password: MAVEN_REPO_PASSWORD
    - name: cattest
      run: cat /home/runner/.m2/settings.xml
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish Package
      run: mvn deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
        MAVEN_USERNAME: ${{ secrets.MAVEN_REPO_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_REPO_PASSWORD }}

